### ISSUE TITLE
Can you provide pretrained weights? 

### ISSUE THREAD

**Issue by Jiakui** [InnerPeace-Wu/densecap-tensorflow#1]
Hi, 

Can you provide pretrained weights? Thanks!

Jiakui Wang

**Comment by InnerPeace-Wu** [comment]
Hi,
of course. Kinda busy these days, maybe tomorrow or so.

**Comment by InnerPeace-Wu** [comment]
Already upload the pretrained model with iters 500k, please check the README in latest commit.
best.
