### ISSUE TITLE
"Broken pipe issue" from meteor.py

### ISSUE THREAD

**Issue by juliuswang0728** [InnerPeace-Wu/densecap-tensorflow#10]
Hi, 

This issue seems more of stemming from coco caption tool, but would you like to comment any possible way to get around it? So, the error raises within `meteor.py` as follows, 

```
Traceback (most recent call last):
  File "../tools/test_net.py", line 142, in <module>
    vis=args.vis, use_box_at=args.use_box_at, save_html_path=args.save_html_dir)
  File "/scratch/work/xxxx/Projects/densecap/tools/../lib/dense_cap/test.py", line 481, in test_net
    vg_evaluator.evaluate()
  File "/scratch/work/xxxx/Projects/densecap/tools/../lib/pycocoevalcap/vg_eval.py", line 118, in evaluate
    score_match, scores_match = Meteor().compute_score(gts_tokens_match, res_tokens_match, imgIds=all_keys)
  File "/scratch/work/xxxx/Projects/densecap/tools/../lib/pycocoevalcap/meteor/meteor.py", line 47, in compute_score
    stat = self._stat(res[i][0], gts[i])
  File "/scratch/work/xxxx/Projects/densecap/tools/../lib/pycocoevalcap/meteor/meteor.py", line 96, in _stat
    self.meteor_p.stdin.write('{}\n'.format(score_line))
IOError: [Errno 32] Broken pipe
```

It happens in a for loop given below (also in `meteor.py`), 
```
        for i in imgIds:
            print 'img IDs:', i
            assert(len(res[i]) == 1)
            stat = self._stat(res[i][0], gts[i])
            print 'stat:', stat
            eval_line += ' ||| {}'.format(stat)
```
The first execution of the for loop is fine, but the second time it enters the loop, specifically, getting into `stat = self._stat(res[i][0], gts[i])`, then the error pops up. 
 
I am aware of there had been posts asking the exact same issue (e.g. [https://github.com/elliottd/satyrid/issues/2](https://github.com/elliottd/satyrid/issues/2)), but just couldn't find myself a workaround after spending few hours on it. Have you ever encountered this?

Thanks in advance, and any idea would be really appreciated :)

**Comment by InnerPeace-Wu** [comment]
Hi,
I did not encounter the issue, but i think you may refer to [official repo of it](https://github.com/tylin/coco-caption/issues/17) where the same problem is reported, and offered several options.
Best,

**Comment by juliuswang0728** [comment]
Hi, 

Sorry to be this late to get back to you. I resolved the issue and it was simply by having `paraphrase-en.gz` (for example, grab it from [here](https://github.com/lichengunc/refer/tree/master/evaluation/meteor/data)) placed in `./tools/pycocoevalcap/meteor/data`. I'll close the issue and thanks for you help :)

**Comment by zhangbinxy** [comment]
Yes, it works.

**Comment by DeepaliVerma** [comment]
file is already present in the respective location, still i m facing the same issue.
