### ISSUE TITLE
ImportError: lib/utils/bbox.so: failed to map segment from shared object

### ISSUE THREAD

**Issue by ShinDongHwan** [InnerPeace-Wu/densecap-tensorflow#13]
i'm interested in captioning. so i've tried to train.
but  following message was output.

> File "./tools/train_net.py", line 32, in <module>
>     from lib.datasets.factory import get_imdb
>   File "/DataStorage/dhshin/image_caption/densecap-tensorflow/tools/../lib/datasets/factory.py", line 11, in <module>
>     from visual_genome import visual_genome
>   File "/DataStorage/dhshin/image_caption/densecap-tensorflow/tools/../lib/datasets/visual_genome.py", line 20, in <module>
>     from lib.datasets.imdb import imdb
>   File "/DataStorage/dhshin/image_caption/densecap-tensorflow/tools/../lib/datasets/imdb.py", line 24, in <module>
>     from lib.utils.bbox import bbox_overlaps
> ImportError: /DataStorage/dhshin/image_caption/densecap-tensorflow/tools/../lib/utils/bbox.so: failed to map segment from shared object

i refered 
"bash scripts/dense_cap_train.sh [dataset] [net] [ckpt_to_init] [data_dir] [step]"

And my command is 
"bash scripts/dense_cap_train.sh visual_genome_1.2 res101 /DataStorage/dhshin/image_caption /DataStorage/dhshin/ic_dataset/visual_genome/VG_100K/ 1"

dataset: visual_genome_1.2
net: res101
ckpt_to_init: /DataStorage/dhshin/image_capton
data_dir: /DataStorage/dhshin/ic_dataset/visual_genome/VG_100K

resnet101.ckpt file exists in"/DataStorage/dhshin/image_capton" 
image files exist in "/DataStorage/dhshin/ic_dataset/visual_genome/VG_100K"

i don't know why this error occure. i need your help. 
Thank you for your kind answers.

**Comment by InnerPeace-Wu** [comment]
Hi,
did you compile the local libs properly? [Link for the very step](https://github.com/InnerPeace-Wu/densecap-tensorflow#compile-local-libs)

**Comment by InnerPeace-Wu** [comment]
The problem is that **I don't have the `./lib/utils/bbox.so` after the compiling, instead, i get `cython_bbox.so`**, you may refer to [link](https://github.com/endernewton/tf-faster-rcnn#installation) and re-compile again to see how it goes.
best,

**Comment by ShinDongHwan** [comment]
Thank you. but i faced same warning on "Build the Cython modules".

i edited "utils.cython_bbox" to "utils.bbox" on ["setup.py"](https://github.com/endernewton/tf-faster-rcnn/blob/0e61bacf863f9f466b54770f35a130514e85cac6/lib/setup.py#L109)

but i can't solve.TT

**Comment by InnerPeace-Wu** [comment]
How about editing it back to  "utils.cython_bbox"? Warnings are fine, I did not pay much attention to the compiling procedure though, i suppose the names are somehow related.

**Comment by ShinDongHwan** [comment]
Thank you for kindly answer!^^ 
I'll try to solve the problem until solved. 
Could i ask last question?

> And my command is
> "bash scripts/dense_cap_train.sh visual_genome_1.2 res101 /DataStorage/dhshin/image_caption /DataStorage/dhshin/ic_dataset/visual_genome/VG_100K/ 1"

> dataset: visual_genome_1.2
> net: res101
> ckpt_to_init: /DataStorage/dhshin/image_capton
> data_dir: /DataStorage/dhshin/ic_dataset/visual_genome/VG_100K
> 
> resnet101.ckpt file exists in"/DataStorage/dhshin/image_capton"
> image files exist in "/DataStorage/dhshin/ic_dataset/visual_genome/VG_100K"

Are parameters okay?

**Comment by InnerPeace-Wu** [comment]
ckpt_to_init: for the first time training, you'd better specify the **full path to ckpt file** like: `/DataStorage/dhshin/image_capton/resnet101.ckpt`
data_dir: it should the directory where you put the files of **preparing step**, i.e. the output directory of `preprocess.py`.

**Comment by ShinDongHwan** [comment]
Thank you!!
Your kind reply has been a lot to me.
