### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'astype'

### ISSUE THREAD

**Issue by Dontfall** [InnerPeace-Wu/densecap-tensorflow#15]
当运行bash scripts/dense_cap_train.sh [dataset] [net] [ckpt_to_init] [data_dir] [step]时，出现如下bug:
.......
.......
Loaded.
Fix Resnet V1 layers..
Fixed.
Ckpt path: /home/xiewei/densecap-tensorflow/slim_models/res50.ckpt
Traceback (most recent call last):
  File "./tools/train_net.py", line 214, in <module>
    main()
  File "./tools/train_net.py", line 210, in main
    max_iters=args.max_iters)
  File "/home/xiewei/densecap-tensorflow/tools/../lib/dense_cap/train.py", line 485, in train_net
    sw.train_model(sess, max_iters)
  File "/home/xiewei/densecap-tensorflow/tools/../lib/dense_cap/train.py", line 356, in train_model
    blobs = self.data_layer.forward()
  File "/home/xiewei/densecap-tensorflow/tools/../lib/fast_rcnn/layer.py", line 99, in forward
    blobs = self._get_next_minibatch()
  File "/home/xiewei/densecap-tensorflow/tools/../lib/fast_rcnn/layer.py", line 95, in _get_next_minibatch
    return get_minibatch(minibatch_db)
  File "/home/xiewei/densecap-tensorflow/tools/../lib/fast_rcnn/minibatch.py", line 41, in get_minibatch
    im_blob, im_scales, roidb = _get_image_blob(roidb, random_scale_inds)
  File "/home/xiewei/densecap-tensorflow/tools/../lib/fast_rcnn/minibatch.py", line 101, in _get_image_blob
    cfg.TRAIN.MAX_SIZE)
  File "/home/xiewei/densecap-tensorflow/tools/../lib/utils/blob.py", line 37, in prep_im_for_blob
    im = im.astype(np.float32, copy=False)
AttributeError: 'NoneType' object has no attribute 'astype'
 请问，如何解决？谢谢！

**Comment by InnerPeace-Wu** [comment]
Please refer to [the same issue](https://github.com/InnerPeace-Wu/densecap-tensorflow/issues/12)
best

**Comment by Dontfall** [comment]
It works.
Thank you!
**Download images Part1 and Part2, extract all (two parts) to directory VG/images.**I got it wrong .
Original directory：
 --VG
   --1.2
      --image_data.json
      --region_descriptions.json
      --regions
   --images
      --VG_100K
      --VG_100K_2

Correct directory:
 --VG
   --1.2
      --image_data.json
      --region_descriptions.json
      --regions
   --images

**Comment by Dontfall** [comment]
Original directory：
——VG
   |——1.2
        |——image_data.json
        |——region_descriptions.json
        |——regions
   |——images
        |——VG_100K
        |——VG_100K_2

Correct directory:
——VG
   |——1.2
        |——image_data.json
        |——region_descriptions.json
        |——regions
   |——images

**Comment by Dontfall** [comment]
It works.
Thank you!
**Download images Part1 and Part2, extract all (two parts) to directory VG/images.**I got it wrong .
Original directory：
└── VG
    ├── 1.2
    │   ├── image_data.json
    │   ├── region_descriptions.json
    │   ├── regions
    └── images
        ├── VG_100K
        └── VG_100K_2

Correct directory:
└── VG
    ├── 1.2
    │   ├── image_data.json
    │   ├── region_descriptions.json
    │   ├── regions
    └── images

**Comment by Dontfall** [comment]
It works.
Thank you!
**Download images Part1 and Part2, extract all (two parts) to directory VG/images.**I got it wrong .
Original directory：
└── VG
├── 1.2
│ ├── image_data.json
│ ├── region_descriptions.json
│ ├── regions
└── images
├── VG_100K
└── VG_100K_2

Correct directory:
└── VG
├── 1.2
│ ├── image_data.json
│ ├── region_descriptions.json
│ ├── regions
└── images

**Comment by Dontfall** [comment]
It works.
Thank you!
**Download images Part1 and Part2, extract all (two parts) to directory VG/images.**I got it wrong .
Original directory：
└── VG
├── 1.2
│ ├── image_data.json
│ ├── region_descriptions.json
│ ├── regions
└── images
├── VG_100K
└── VG_100K_2

Correct directory:
└── VG
├── 1.2
│      ├── image_data.json
│ ├── region_descriptions.json
│ ├── regions
└── images

**Comment by Dontfall** [comment]
It works.
Thank you!
**Download images Part1 and Part2, extract all (two parts) to directory VG/images.**I got it wrong .
![2018-06-11 10-59-09](https://user-images.githubusercontent.com/28423651/41210852-8c693d0a-6d66-11e8-878e-5397e4a52f69.png)

**Comment by Dontfall** [comment]
@InnerPeace-Wu 
It works.
Thank you!
**Download images Part1 and Part2, extract all (two parts) to directory VG/images.**I got it wrong .
![2018-06-11 10-59-09](https://user-images.githubusercontent.com/28423651/41210943-fe45e52c-6d66-11e8-8b0b-beec9d9e048d.png)
