### ISSUE TITLE
Question about stop_gradient of the coordinates generated by rpn

### ISSUE THREAD

**Issue by Jiakui** [InnerPeace-Wu/densecap-tensorflow#2]
According to Li Feifei's paper on densecap,  they mention that they were using the bilinear sampling method, thus the gradients can be propagated backward into predicted region proposal coordinates.  

It seems that your code is using stop_gradient before  crop_and_resize. I am curious whether Li Feifei's strategy really matters. 

How do you think about it? 

Thanks!

**Comment by InnerPeace-Wu** [comment]
Hi,
You may check Linjie's [paper](https://arxiv.org/abs/1611.06949). They discussed about it, and experiments showed that stop gradient will be better.
