### ISSUE TITLE
 Hierarchical description of the image 

### ISSUE THREAD

**Issue by Jiakui** [InnerPeace-Wu/densecap-tensorflow#3]
Li feifei has another paper, generate coherent long sentences to describe an image using hierarchical attention method.  It seems that the hierarchical attention method is extended from the dense cap method, thus I am wondering whether it is possible to implement the hierarchical attention model based on your current code.

Do you have any suggestion?

**Comment by Jiakui** [comment]
If it's convenient for you, can we chat on 微信 ？ my account is   sherchy   ，thanks!

**Comment by InnerPeace-Wu** [comment]
You mean the paper "A Hierarchical Approach for Generating Descriptive Image Paragraphs"? I did not read it through, so I have no suggestion currently. Sorry about it.
I am glad to make a friend, but if you have anything about the project, I would suggest you to post here, and I will reply ASAP, which might help others sharing the same question. Thanks.
中文也可以的。^_^

**Comment by Jiakui** [comment]
I think if we could extend this project to  implement "A Hierarchical Approach for Generating Descriptive Image Paragraphs", the significance of the current project can be enhanced by a lot. It should be worthwhile to have a try.

**Comment by InnerPeace-Wu** [comment]
It is a good idea, I will read through the paper firstly to see what i can do. But for now, I am after several ddls. I do encourage you to follow it up. 
best,

**Comment by InnerPeace-Wu** [comment]
I am working on it, pls refer the [repo](https://github.com/InnerPeace-Wu/im2p-tensorflow) for more details.
best,
