### ISSUE TITLE
glove embedding

### ISSUE THREAD

**Issue by princeamitlali** [InnerPeace-Wu/densecap-tensorflow#30]
i am working on the densecap and have a little confusion about the embedding as i wanted to train the same model on diffrent language. and also glove embedding is only for english so,
i have to use some other embedding?
if yes please suggest where to use the same?
thank you

**Comment by zhangbinxy** [comment]
Hello, did you fix it?

**Comment by zhangbinxy** [comment]
I have happened to this problem ! Did you solve it ? @princeamitlali 
Thanks!!!

**Comment by princeamitlali** [comment]
Respected,
Yes I solved it.you have to download the GloVe embedding from there
official website. Also please ensure the embedding dimensions they
mentioned. so please ensure to download 300-dimension glove vector having 6
billion words .and also u need to bring some changes into some file.
In pre_glove.py give the path of glove vector.
In densecao_oa_test.sh set Train_GLOVE to True
In dense_cap_config.yml set INIT_BY_GLOVE True.  KEEP_AS_GLOVE_DIM AS True

In network.py give path of glove

In config.py set _C.INIT_BY_GLOVE as True


Thats all

prince amit

**Comment by princeamitlali** [comment]
yes.i solved it by using other embeddings. i was working using hindi language so i choose fasttext devloped by facebook for the same also u have to edit some files.

**Comment by zhangbinxy** [comment]
Thank you for your reply! @princeamitlali , I am searching where the embedding is, but sadly I've not been finding the original glove embedding so that replacing seems impossible. Could you kindly share your method? Thanks a lot!!!

**Comment by princeamitlali** [comment]
Here is the website you can download glove embedding from here

https://nlp.stanford.edu/projects/glove/

Please choose glove.6b zip file that is of 800+ mb

**Comment by zhangbinxy** [comment]
You are so kindhearted @princeamitlali.
Actually, perhaps my explanation is not clear. I mean that I cannot find the glove embedding position If I want to change it when my plan is to use another language instead of English, so could you give me a suggestion?
Thank you !!!

**Comment by zhangbinxy** [comment]
It seems no glove embedding in the code file, and even no use of it. I don't know if I make a mistake for understanding that.

**Comment by princeamitlali** [comment]
You have to download and put the glove.6b  manually in data
directory.altough the code can work without glove embedding.but using glove
embedding will improve the results. As author use glove embedding to get
that result you also have to use it otherwise result will be lesser.

**Comment by zhangbinxy** [comment]
Yes, you are right. When you train the model on a different language dataset, have you had any problem like encoding or others? I am suffering from this right now.

**Comment by princeamitlali** [comment]
Yes, encoding created the problem as we are using Hindi and glove is not
for Hindi.so we have to shift for another embedding vector known as
fasttext brought to by Facebook. Which language you are using?

**Comment by zhangbinxy** [comment]
Thanks @princeamitlali , I have just made it training and the output of debug seems normal, that is to say that I can get sentences comprised of number. I am trying the model with Chinese, although embedding has not yet been used. If you have completed training, could you share your outcome or mAP? As you said before that embedding was better than no embedding, is the difference huge? Thank you!

**Comment by princeamitlali** [comment]
Actually I work on the same during my internship period. So , sorry I don't
have results to show you.

**Comment by zhangbinxy** [comment]
Thank you all the same !
