### ISSUE TITLE
where is result.json in the demo.py?

### ISSUE THREAD

**Issue by joyce9533** [InnerPeace-Wu/densecap-tensorflow#35]
I came into this error:

File "./tools/demo.py", line 129, in <module>
    with open(save_path + '/results.json', 'w') as f:
IOError: [Errno 2] No such file or directory: './vis/data/results.json'

**Comment by batooooo** [comment]
hi i got same problem
did you solved it?

**Comment by joyce9533** [comment]
> hi i got same problem
> did you solved it?

yeah, just create a folder 'data' under 'vis', it works for me, good luck!
