### ISSUE TITLE
How do you initialize "context feature" ? 

### ISSUE THREAD

**Issue by Jiakui** [InnerPeace-Wu/densecap-tensorflow#4]
In the context fusion mode,  _global_roi  is used as the context feature . However, I don't quite understand how you calculate the _global_roi from scratch. Can you give me any hint? 

Thanks!

**Comment by InnerPeace-Wu** [comment]
I made _global_roi a placeholder, and feed it in CONTEXT_MODE, check [code](https://github.com/InnerPeace-Wu/densecap-tensorflow/blob/ce70133d87820f7e5d0e74ad77ae89cfae5f5b9d/lib/nets/network.py#L883).  After _global_roi is created, we [concatenate](https://github.com/InnerPeace-Wu/densecap-tensorflow/blob/ce70133d87820f7e5d0e74ad77ae89cfae5f5b9d/lib/nets/network.py#L747) it to **rois** for later use.
Besides, _global_roi is just a 5-D array with info of the image size.

**Comment by Jiakui** [comment]
Yes, I see it. Actually, _global_roi is just the image size, so that after crop_and_resize, the global feature map of the image was resized and added as one rois . 

How do you compare the idea of context fusion to visual attention? Is there any similarity between these two ideas? 

thanks

**Comment by InnerPeace-Wu** [comment]
I think the context fusion is about looking at the details with big picture in mind, and visual attention over the whole image feature could do the same trick reasonably.
