### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by batooooo** [InnerPeace-Wu/densecap-tensorflow#40]
hello 
when i try to this 
$ cd $ROOT/lib
$ python preprocess.py --version [version] --path [raw_data_path] \
        --output_dir [dir] --max_words [max_len]$ cd $ROOT/lib ,

i have type error..

split image number: 77398 for split name: train
start loading json files...
10.529908 seconds for loading
train:   0%|                                                                                                                                                                     | 0/108077 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "preprocess.py", line 226, in <module>
    process_vg()
  File "preprocess.py", line 222, in process_vg
    vocab = process_dataset(split_name, vocab=vocab)
  File "preprocess.py", line 196, in process_dataset
    split_ids=split_image_ids, vocab=vocab)
  File "preprocess.py", line 117, in __init__
    obj['phrase_tokens'] = phrase.translate(None, string.punctuation).split()
TypeError: a bytes-like object is required, not 'str'

how to fix it?

**Comment by Anth0nyWu** [comment]
So how did you solve it please.
