### ISSUE TITLE
Very Slow Processing Time

### ISSUE THREAD

**Issue by Hakan79** [InnerPeace-Wu/densecap-tensorflow#8]
Hi,

It takes more than 1 minute to process 1 image.

I ran the bash scripts/dense_cap_demo.sh ./output/ckpt ./output/ckpt/vocabulary.txt  command.

I wonder if I am doing anything wrong.   I am using an aws p2.xlarge gpu.  Is this normal ?

Or do have to do another configuration I am not aware of.  Please any help is appreciated.

Thanks

**Comment by InnerPeace-Wu** [comment]
Hi,
I tested once, K80 is slower than gtx 10xx. You may change the config `TEST.USE_BEAM_SEARCH` in `scripts/dense_cap_demo.sh` to be **False** and it will be faster.
best,

**Comment by Hakan79** [comment]
Hi,

Thanks I did change it and it was a lot faster.  Good job on the code !   Thanks

**Comment by InnerPeace-Wu** [comment]
Glad to help.
I will close the issue, but feel free to reopen it if you have further question.
best
