### ISSUE TITLE
ckpt_to_init: pretrained model to be initialized with. Refer to tf_faster_rcnn for more init weight details.

### ISSUE THREAD

**Issue by liuxx2016** [InnerPeace-Wu/densecap-tensorflow#9]
how to get ckpt_to_init in details

**Comment by InnerPeace-Wu** [comment]
Please refer to https://github.com/endernewton/tf-faster-rcnn/blob/master/README.md#train-your-own-model, it has great details.
best,

**Comment by liuxx2016** [comment]
Thank you for your reply. Am I going to train the model? Or just download the pre-trained model like res101.ckpt?

**Comment by InnerPeace-Wu** [comment]
You can run the demo with instructions of https://github.com/InnerPeace-Wu/densecap-tensorflow#demo. If you would like to train your own model, you have to follow the steps in README, e.g. setting up dependencies, pre-processing training data etc. and train the densecap model.

**Comment by liuxx2016** [comment]
我的英文不好，请见谅。
我按照README 中的指导配置好了运行环境，现在我想从头开始训练模型。已做到：
`**bash scripts/dense_cap_train.sh [dataset] [net] [ckpt_to_init] [data_dir] [step]**`
对于最初的权重初始化，[ckpt_to_init] 中的初始化权重是自己生成的么？我看到faster-rcnn中直接采用了slim的预训练模型。我看到您的代码：
**`ckpt_path="experiments/random_fixconv_i85k_171219/dc_fixed_1219/vg_1.2_train`**
这里的初始化权重您是如何生成得到的？多谢～

**Comment by InnerPeace-Wu** [comment]
没关系的，用英文只是为了方便其它有同样问题的人相互交流。
[ckpt_to_init] 这个权重就是slim的预训练模型。
```sh
ckpt_path="experiments/random_fixconv_i85k_171219/dc_fixed_1219/vg_1.2_train
```
这部分代码是我在已经训练一定时间之后的权重基础上进行再训练。如果你重新训练这里就用slim的预训练模型所在的路径。
